### ISSUE TITLE
Bug In [Orks and Speed Freakz]

### ISSUE THREAD

**Issue by goosington** [ksnyder1986/Warhammer-40k-3rd-Edition#102]
**Describe the bug**
List verification says warboss needs 5 nobz, he may take nobz and if he does he must take 5.
If you take any retinue (meks or mad doks) the verification makes you take 5 nobz.

Also, mega armor on warboss and nobz demands you take two handed weapon. Mega armor comes with own weapons.

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: orks and speedfreakz
2. Unit: warboss
3. Option: mega armor and retinue
4. Issue: see above
![Screenshot_20240124_000645](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/48977426/8411e9b9-604f-4625-9dc0-906703193bc8)

**Comment by ksnyder1986** [comment]
I cannot replicate the two-handed weapon issue. Can you show me the exact selection you made that caused that?

For the Nobz, my reading of the Bodyguard rule implies you cannot have Mekboyz or Mad Doks without first taking the 5 Nobz. Do you think I am reading that wrong, or was their a FAQ or something that changed that?

**Comment by goosington** [comment]
You are correct on bodyguard rule, my apologies.

As for mega armor, two handed issue is still present. Minimum requirement is still that nobz have to have a two handed weapon. See attached.
![Uploading Screenshot_20240709_114551.jpg…]()

**Comment by ksnyder1986** [comment]
I still cannot replicate this issue.
