### ISSUE TITLE
[Anon] Imperial Guard (2003): The infantry platoon squad only allows you to Eddit options for one squad not both and the command

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#123]
**Problem:**
The infantry platoon squad only allows you to Eddit options for one squad not both and the command

**Expected:**
Split the squads out so they are listed as squad 1 and squad 2 

**List:** https://www.newrecruit.eu/app/list/SAuAr
**Unit:** Infantry Squad, id: `04f8-57a2-d5ec-8800`

**Comment by ksnyder1986** [comment]
This is a New Recruit UI problem. It is possible to split the squads apart.
