### ISSUE TITLE
[Anon] Imperial Guard (2003): Grenadiers do not get options from regimental doctrines

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#124]
**Problem:**
Grenadiers do not get options from regimental doctrines

**Expected:**
Grenadiers troops choice should be able to select Hardened Fighters and Deep Strike from the relevant regimental doctrines

**List:** https://www.newrecruit.eu/app/list/ZqxkZ

**Comment by ksnyder1986** [comment]
Grenadiers are Storm Troopers. They do not count as Guard Infantry (page 55). Therefore they cannot be given Hardened Fighters or Drop Troops rules.
