### ISSUE TITLE
[Anon] Imperial Guard (2003): Leman Russ in Warhammer 40k 3E does not include track guards in vehicle upgrades

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#126]
**Problem:**
Leman Russ in Warhammer 40k 3E does not include track guards in vehicle upgrades

**Expected:**
The track guards are available to all Imperial Guard vehicles other than sentinels according to the 2003 codex.

 **Additional Info:**
2003 Imperial Guard codex, page 36

**List:** https://www.newrecruit.eu/app/list/BBKUV
**Unit:** Leman Russ, id: 6070-a00d-1753-fc66

**Comment by ksnyder1986** [comment]
The unit entry has track guards. I am unsure what this bug is.
