### ISSUE TITLE
[Anon] Space Wolves (2000): Blood Claws cannot take Rhino

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#136]
**Problem:**
Blood Claws cannot take Rhino

**Expected:**
8-15 Blood Claws can take a Rhino at +50 points

 **Additional Info:**
Space Wolves Codex, Warhammer 40k 3rd edition

**List:** https://www.newrecruit.eu/app/list/yUfy7

**Comment by HeyGMKenny** [comment]
When the Blood Claws go beyond the mandatory 8 models, the Rhino becomes bugged/hidden. 
![blood claws](https://github.com/user-attachments/assets/b2a68488-5154-4ee3-8db1-7335ecc35fb1)
