### ISSUE TITLE
[Anon] Witch Hunters (2003): Razorback missing upgrade options

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#137]
**Problem:**
Razorback missing upgrade options

**Expected:**
Razorbacks can equip: dozer blades, extra armor, hunter-killer missile, pintle-mounted storm bolter, searchlight, or smoke launchers at the same cost as the Rhino. Razorbacks can also carry an "entire unit" of Grey Hunters, up to 10 Space Marines, instead of the standard 6. 

 **Additional Info:**
Warhammer 40k 3rd edition Space Marines Codex page 11. Warhammer 40k 3rd edition Space Wolves codex page 10

**List:** https://www.newrecruit.eu/app/list/Uh97F

**Comment by ksnyder1986** [comment]
Razorbacks are fixed to 6 models, regardless of whether they are from codex space marine or codex space wolves
