### ISSUE TITLE
[Anon] Imperial Guard (2003): Rough Riders have incorrect points cost for special weapons

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#139]
**Problem:**
Rough Riders have incorrect points cost for special weapons

**Expected:**
Flamer should be +6, melta and plasma should be +10, grenade launcher should be +8

**Comment by ksnyder1986** [comment]
Not a bug. The cost of the special weapon rough rider includes the 8 points for the rough rider, therefore the costs may appear higher than the book
