### ISSUE TITLE
[Anon] Chaos Space Marines (2002): Ahriman is missing

### ISSUE THREAD

**Issue by NewRecruitAnon** [ksnyder1986/Warhammer-40k-3rd-Edition#140]
**Problem:**
Ahriman is missing

**Expected:**
Ahriman profile should be available :)

**List:** https://www.newrecruit.eu/app/list/zsTOO

**Comment by ksnyder1986** [comment]
Not a bug. Ahriman will appear if you select the Thousand Sons book of chaos
