### ISSUE TITLE
Chapter Approved Sisters of Battle

### ISSUE THREAD

**Issue by ksnyder1986** [ksnyder1986/Warhammer-40k-3rd-Edition#15]
### Buildout
- [ ] Basic Army Structure
  - [ ] Canoness
  - [ ] Celestine Superior
  - [ ] Celestian Bodyguard
  - [ ] Dominion Squad
  - [ ] Celestian Squad
  - [ ] Priestly Delegation
  - [ ] Battle Sisters
  - [ ] Redemptionists
  - [ ] Rhino
  - [ ] Seraphim
  - [ ] Mounted Battle Sisters
  - [ ] Retributor Squad
  - [ ] Immolator
  - [ ] Exorcist
- [ ] Armoury
- [ ] Chapter Approved
- [ ] Imperial Armoury
- [ ] Rule Descriptions

### Validation
- [ ] Basic Army Structure
  - [ ] Canoness
  - [ ] Celestine Superior
  - [ ] Celestian Bodyguard
  - [ ] Dominion Squad
  - [ ] Celestian Squad
  - [ ] Priestly Delegation
  - [ ] Battle Sisters
  - [ ] Redemptionists
  - [ ] Rhino
  - [ ] Seraphim
  - [ ] Mounted Battle Sisters
  - [ ] Retributor Squad
  - [ ] Immolator
  - [ ] Exorcist
- [ ] Armoury
- [ ] Chapter Approved
- [ ] Imperial Armoury
- [ ] Rule Descriptions

**Comment by hutber** [comment]
Fantastic, I was looking today for Sisters as it goes!!
I am confused if this is actively being maintained?

**Comment by hutber** [comment]
NICE!!! :D
