### ISSUE TITLE
Issues in Catachans Deathworld Veterans Roster

### ISSUE THREAD

**Issue by Pibutzki** [ksnyder1986/Warhammer-40k-3rd-Edition#60]
**Describe the bug**

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: Catachans
2. Unit: Deathworld Veteran Command HQ
3. Option: Deathworld Veteran
4. Issue: Does not calculate the base cost of a Deathword Veteran (9pts), only the additional costs of upgrades (medic, Comm-Link, Special Weapons)

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: Catachans
2. Unit: Deathworld Veteran Officers
3. Option: Imperial Guard Armoury; Wargear
4. Issue: Honorifica Imperialis, Macharian Cross missing from wargear options. Master-Crafted Weapon can only be taken once, possible combination should be one MC ranged weapon and one MC CCW

**Additional context**

**Comment by ksnyder1986** [comment]
> **Roster and Unit/Upgrade Issue** Please describe exactly where the problem is:
> 
> 1. Roster: Catachans
> 2. Unit: Deathworld Veteran Officers
> 3. Option: Imperial Guard Armoury; Wargear
> 4. Issue: Honorifica Imperialis, Macharian Cross missing from wargear options. Master-Crafted Weapon can only be taken once, possible combination should be one MC ranged weapon and one MC CCW

Can you confirm that the Mater-crafted weapon is allowed to be taken twice? This was the one wargear option I was not certain about. Do you have an errata or FAQ?

**Comment by Pibutzki** [comment]
I'm guessing you are working off the 1999 IG Codex where the wargear restrictions are worded different. That also explains the omissions of Honorifica Imperialis and Macharian Cross since they seem to be added in the 2003 Codex. Concerning wargear, the -03 dex says "You may not take duplicate items for the same model but may have more than one master-crafted weapon."

**Comment by ksnyder1986** [comment]
Correct. I considered making a "2003 update" version of the deathworld veterans, but it felt like the 2003 codex gave that option with the custom regiments. I don't remember at the time if the idea was the 2003 codex replaced the 1999 codex and all of the variants published in-between or not.

**Comment by ksnyder1986** [comment]
Everything addressed except for the 2 medals
