### ISSUE TITLE
Bug In Craftworld Eldar

### ISSUE THREAD

**Issue by dsmaddalena** [ksnyder1986/Warhammer-40k-3rd-Edition#66]
**Describe the bug**
Shadow Weavers are seemingly tied to the Shuriken Cannon id. Points are correct and the roster view indicates I chose Shadow Weavers, but the weapon summary in roster view display it as a Shuriken Cannon.

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: Craftworld Eldar
2. Unit: Support Weapon Platform (Heavy)
3. Option: Shadow Weaver
4. Issue: Shadow Weaver weapon not displayed; Shuriken Cannon stats and name displayed instead

**Comment by ksnyder1986** [comment]
Thanks, fixed
