### ISSUE TITLE
Bug In Craftworld Eldar

### ISSUE THREAD

**Issue by dsmaddalena** [ksnyder1986/Warhammer-40k-3rd-Edition#67]
**Describe the bug**
Biel-Tan Swordwind list has validation error when selecting more than three units of Troops, says I can't have that many Elites. It won't complain if I load up with the Swordwind Elites and if taken by themselves it'll let me take six units of Storm Guardians. However, if my number of units in Troops plus the number of the vanilla eldar Troops that are now in Elites goes above six, validation error on number of troops. 

Examples:
4x units Fire Dragons (Too Many Elites)
3x units Fire Dragons 4x units Storm Guardians (Too Many Troops, Too Many Elites... it thinks there are 7 of each)

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: Craftworld Eldar
2. Unit: Troops/Elites composition
3. Option: Any units in Troops/Elites
4. Issue: Force composition validation is all mucked up.

**Comment by ksnyder1986** [comment]
Thanks, fixed
