### ISSUE TITLE
Chaos Space Marine Roster issues

### ISSUE THREAD

**Issue by MCRubles** [ksnyder1986/Warhammer-40k-3rd-Edition#81]
Hey same guy as before. I found some more issues with the roster when I went through the CSM codex:

Roster: Chaos Space Marines (2002)

Unit: Chaos Dreadnought
Option: Blastmaster
Issue: Blastmaster is not twin linked (Pg 56)

Unit: Possessed and Havocs
Option: Aspiring Champion upgrade
Issue: Emperor's Children units get a free aspiring champion with 6 models not 5 (Pg 56)

Unit: Abaddon and Fabius Bile
Issue: These two models are not available to Emperor's Children armies (No mark of Slaanesh) (Pg 56)

Unit: Raptors
Issue: They arent on the roster (Pg 32)

Unit: Lucius the Eternal
Issue: Counts as a chaos lord. Cannot be taken with another chaos lord (pg 57)

**Comment by ksnyder1986** [comment]
Should be all, except there Raptors can only take the mark of chaos undivided, so they cannot be Emp Children lists

**Comment by MCRubles** [comment]
Ah, you're right I missed that. Thanks!
