### ISSUE TITLE
Bug In [Roster]

### ISSUE THREAD

**Issue by Kojiro2k** [ksnyder1986/Warhammer-40k-3rd-Edition#84]
**Describe the bug**

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: Orks (1999)
2. Unit: Flash Gitz
3. Option: Special Weapons and Kustom Jobs
4. Issue: in case of spacial weapons thre is option of rockitt launcha two times should be rockitt launcha and big shoota with point value of 8 in terms of Kuston Jobs there is only possibiliby to take one custom job for all the Gitz while there should be a possibility to take one, two or three custom jobs for the entire squad 

**Additional context**

**Comment by ksnyder1986** [comment]
I'm going to fix the big shoota.

For the kustom jobs, I took a picture of the codex entry and it says only one job can be taken for the entire mob. Is there something in an FAQ or Chapter Approved that allow them to take more than one at a time?

![image](https://user-images.githubusercontent.com/54869316/209336011-0dad45e6-ecb5-403f-b075-fed91e982571.png)
