### ISSUE TITLE
How to import into battlescribe with URL?

### ISSUE THREAD

**Issue by hutber** [ksnyder1986/Warhammer-40k-3rd-Edition#90]
I am trying to get a friend through his phone to import the data on BS, is it possible with a URL?

![image](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/1344898/87eb2d78-fd9c-424e-9db4-4648fd28518c)
![image](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/1344898/e686ce5d-1cda-45ee-bdb0-bcdedef6c39f)

**Comment by ksnyder1986** [comment]
https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/wiki/Adding-to-Battlescribe-App

Did you try to follow these instructions?

**Comment by hutber** [comment]
Thanks!

I didn't, however the way to get to the same path is slightly different on the desktop version where i saw the error. I will ask him to try on his phone.

My desktop error.
![image](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/1344898/42da7446-cd73-4ff8-9bf5-8430c8f8a07e)
