### ISSUE TITLE
Bug In [Tyranid Roster]

### ISSUE THREAD

**Issue by goosington** [ksnyder1986/Warhammer-40k-3rd-Edition#97]
**Describe the bug**

Mutable Broods max biomorphs incorrect
Max for warriors is 6, only allows 4. Likewise for others.
Bioweapons do not appear to contribute biomorphs, see Carnifex example on page 40 of codex.

Additional issues:

**Roster and Unit/Upgrade Issue**
Please describe exactly where the problem is:
1. Roster: Tyranid
2. Unit: Mutable Warrior
3. Option: Leaping and Winged
4. Issue:  charges 10 or 14 extra, plus cost per warrior. A group of 4 warriors has leaping cost 50 instead of 40.

**Comment by ksnyder1986** [comment]
Oh dumb me I should have read your whole note above. Ignore the previous comment.

**Comment by goosington** [comment]
Hey mate! Fixed hasn't worked, leaping still 40 points for 3 warriors where it should be 30. Assume same trouble for winged.
Bioplasma is also missing from warriors.
Max biomorphs still wrong for warriors, tyrants, gaunts and carnifex.
I spoke to Andy Chambers about it who agreed that weapons are separate from biomorphs.
![Screenshot_20240117_134709](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/48977426/2910e700-2142-4371-a77e-10bb61df559b)
![Screenshot_20240117_071123_Messenger](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/48977426/64b20d57-ddf0-4f53-8cad-b9f2d624e5c0)

**Comment by ksnyder1986** [comment]
Hmm... I see 30pts on my computer, but I see what you see when I use the app.
![image](https://github.com/ksnyder1986/Warhammer-40k-3rd-Edition/assets/54869316/d7902e66-75fa-4fa7-9ea1-cf61256c65f4)

**Comment by ksnyder1986** [comment]
This is trouble. I completely uninstalled and reinstalled the app on Android. That fixed it...
